# Generated by Django 3.2.6 on 2021-08-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelQ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelQQ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_address', models.CharField(max_length=100)),
                ('latitude_coordinate_x', models.FloatField()),
                ('longtitude_coordinate_y', models.FloatField()),
                ('distance_to_MKAD', models.CharField(max_length=100)),
                ('id_modelQ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Program.modelq')),
            ],
        ),
    ]
